# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    sonata.admin.pokemon:
        class: AppBundle\Admin\PokemonAdmin
        arguments: [~, AppBundle\Entity\Pokemon, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Pokemon", label: "Pokemon" }
    sonata.admin.type:
        class: AppBundle\Admin\TypeAdmin
        arguments: [~, AppBundle\Entity\Type, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Pokemon", label: "Type" }
    sonata.admin.trainer:
        class: AppBundle\Admin\TrainerAdmin
        arguments: [~, AppBundle\Entity\Trainer, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Pokemon", label: "Trainer" }
