<?php

namespace AppBundle\Entity;

use Doctrine\ORM\AbstractQuery;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\Expr as Expr;

/**
 * PokemonRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PokemonRepository extends EntityRepository
{
    public function findCatchThemAll()
    {
        $qb = $this->createQueryBuilder('p');

        $qb
            ->select('p, t')
            ->join('p.types', 't', Expr\Join::WITH)
        ;

        $qb->orderBy('p.id', 'DESC');

        return $qb->getQuery()->getArrayResult();
    }

    public function findCatchIt($id)
    {
        $qb = $this->createQueryBuilder('p'); // After: $qb->select('p');

        $qb
            ->select('p, t')
            ->join('p.types', 't', Expr\Join::WITH)
            ->where('p.id = :id')
            ->setParameters([
                ':id' => $id,
            ])
        ;

        return $qb->getQuery()->getSingleResult(AbstractQuery::HYDRATE_ARRAY);
    }
}
