<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PokemonRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PokemonRepository extends EntityRepository
{
    public function findCatchThemAll()
    {
        $qb = $this->createQueryBuilder('p');

//        $qb->andWhere(
//            $qb->expr()->like('p.name', '%a%')
//        );

        return $qb->getQuery()->getArrayResult();
    }
}
