<?php

namespace AppBundle\Entity;

use Doctrine\ORM\AbstractQuery;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\Expr as Expr;

/**
 * PokemonRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PokemonRepository extends EntityRepository
{
    public function findCatchThemAll($id = null)
    {
        $qb = $this->createQueryBuilder('p');

        $qb
            ->select('p, t, tr')
            ->leftJoin('p.types', 't', Expr\Join::WITH)
            ->leftJoin('p.trainer', 'tr', Expr\Join::WITH)
            ->orderBy('p.id', 'DESC')
        ;

        if (null !== $id) {
            $qb
                ->where('p.id = :id')
                ->setParameters([
                    ':id' => $id,
                ])
            ;
        }

        return null === $id
            ? $qb->getQuery()->getArrayResult()
            : $qb->getQuery()->getSingleResult(AbstractQuery::HYDRATE_ARRAY)
        ;
    }
}
